inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  TargetRailsVersion: 7.0
  Exclude:
    - 'bin/*'
    - 'db/**/*'

#################### Layout ##################################

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

#################### Metrics ##################################

# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsblocklength
Metrics/BlockLength:
  Enabled: false
